library(readxl)
Test <- read_excel("D:/FALL25/ADY201m/Test.xlsx")
View(Test)
library(psych)
summary(Test)
attach(Test)
describe(Ram)
describe(Storage)
describe(Battery)
describe(Screen)
describe(Camera_main)
describe(`Camera second`)
describe(Price)